### ISSUE TITLE
Couchbase demo gets stuck bootstrapping

### ISSUE THREAD

**Issue by xer0x** [joyent/mesos-dockerfiles#4]
I tried to run the Couchbase demo on Meso/Marathon and this is what I saw:

This `docker exec` line while bootstrapping keeps looping with an error:
https://github.com/joyent/mesos-dockerfiles/blob/fb71a45699fc87d984af00b91ecc24e451330a47/start-couchbasecluster.sh#L51

```
Waiting to bootstrap Couchbase
.Error response from daemon: problem retrieving container (c7867990-6e0c-11e5-b650-e99c7dd8b3ac)
.Error response from daemon: problem retrieving container (c8c402a0-6e0c-11e5-b650-e99c7dd8b3ac)
```

**Comment by misterbisson** [comment]
Damn, you're right. I hadn't committed a change. It's now in https://github.com/joyent/mesos-dockerfiles/pull/5
